<footer>
  <div class="container-footer">
    <div class="fti">
      <h3>techbar</h3>
      <ul class="content-footer">
        <li><a href="#">123 Melbourne</a></li>
        <li><a href="#">Vic 3000</a></li>
        <li><a href="mailto:info@techbar.com.au">info@techbar.com.au</a></li>
      </ul>
    </div>

    <div class="fti">
      <h3>Useful Link</h3>
      <ul class="content-footer">
        <li><a href="index.php">Home</a></li>
        <li><a href="about.php">About</a></li>
        <li><a href="jobs.php">Careers</a></li>
        <li><a href="apply.php">Apply for Jobs</a></li>
        <li><a href="enhancements.php">Enhancements</a></li>
      </ul>
    </div>

    <div class="fti">
      <p>Subscribe to our Newsletter</p>
        <form action="index.php">
          <input type="email" placeholder="Your email address" required>
          <button type = "submit">Join</button>
        </form>
    </div>
  </div>
</footer>