  <header>
      <nav>
          <div class="logo">
            <img src="images/logo.png" alt="techbar logo" width="94" height="54">
          </div>
          <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="jobs.php">Careers</a></li>
            <li><a href="apply.php">Apply</a></li>
            <li><a href="enhancements.php">Enhancements</a></li>
            <li><a href="manage.php">Manage</a></li>
          </ul>
        </nav>
  </header>
